# Generated by Django 4.2.3 on 2023-12-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='respostaCorreta',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
