# Generated by Django 4.2.3 on 2024-02-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animes', '0002_pergunta_respostacorreta'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizes_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
